### PR TITLE
NXP-32189: expose flexible retention during creation, edit and view

### PR DESCRIPTION
**Pull request by swarnadipa-dev**
https://jira.nuxeo.com/browse/NXP-32189
https://jira.nuxeo.com/browse/NXP-32191
https://jira.nuxeo.com/browse/NXP-32194

### CODE REVIEW

**Review by Nishant0928 — APPROVED** [review]

**Review by rakeshkumar1019 — APPROVED** [review]

**Review by arupmmi07 — APPROVED** [review]
verified

**Comment by guirenard** [comment]
Why there are no translations provided in messages.json like in https://github.com/nuxeo/nuxeo-retention/pull/133/files#diff-3139ffaacd8ac3f5b5e5996e142f26c1d400f4d092f250716503a0de6f059085 ?

**Comment by Nishant0928** [comment]
> Why there are no translations provided in messages.json like in https://github.com/nuxeo/nuxeo-retention/pull/133/files#diff-3139ffaacd8ac3f5b5e5996e142f26c1d400f4d092f250716503a0de6f059085 ?

@guirenard , we already raised and merged a Pr for the translations , so we didnt add it here
https://github.com/nuxeo/nuxeo-retention/pull/135

**Comment by guirenard** [comment]
> > Why there are no translations provided in messages.json like in https://github.com/nuxeo/nuxeo-retention/pull/133/files#diff-3139ffaacd8ac3f5b5e5996e142f26c1d400f4d092f250716503a0de6f059085 ?
> 
> @guirenard , we already raised and merged a Pr for the translations , so we didnt add it here #135

Ok, FYI I don't see any reference to the already merged message key `retention.holdToggleButton.confirm.hold` is it really used?

**Comment by Nishant0928** [comment]
> > > Why there are no translations provided in messages.json like in https://github.com/nuxeo/nuxeo-retention/pull/133/files#diff-3139ffaacd8ac3f5b5e5996e142f26c1d400f4d092f250716503a0de6f059085 ?
> > 
> > 
> > @guirenard , we already raised and merged a Pr for the translations , so we didnt add it here #135
> 
> Ok, FYI I don't see any reference to the already merged message key `retention.holdToggleButton.confirm.hold` is it really used?

yes, we have the translations beforehand , so `retention.holdToggleButton.confirm.hold` will be used in https://jira.nuxeo.com/browse/NXP-32187

**Pull request merged**
